import { z } from 'zod';
import { validate as isUuid } from 'uuid';

/**
 * An administrator's manual credit (> 0) or debit (< 0) with a mandatory reason. The
 * `operationKey` is generated by the caller (the future admin interface) so a double submission
 * records one movement (contracts/admin-wallet.md).
 */
export const recordWalletAdjustmentRequestSchema = z.object({
  amount: z
    .number({ required_error: 'amount is required', invalid_type_error: 'amount must be a number' })
    .int('amount must be a whole number')
    .refine((value) => value !== 0, 'amount must not be 0'),
  reason: z
    .string({ required_error: 'reason is required', invalid_type_error: 'reason must be a string' })
    .trim()
    .min(3, 'reason must have at least 3 characters')
    .max(500, 'reason must have at most 500 characters'),
  operationKey: z
    .string({ required_error: 'operationKey is required', invalid_type_error: 'operationKey must be a string' })
    .refine((value) => isUuid(value), 'operationKey must be a UUID'),
});

export type RecordWalletAdjustmentRequest = z.infer<typeof recordWalletAdjustmentRequestSchema>;
